name: 'Build and install package'
description: 'Build and install python package'
inputs:
  package_file:
    description: "Path to package setup python script."
    required: false
    default: "setup.py"
  working_directory:
    required: false
    default: .
    description: "Working directory to use"
outputs:
  wheel-file:
    description: "Wheel filename"
    value: ${{ steps.wheel.outputs.wheel-file }}
runs:
  using: "composite"
  steps:
    - name: Install python pre-reqs
      run: python -m pip install setuptools wheel twine
      shell: bash
      working-directory: ${{inputs.working_directory}}
    - name: Add IDM artifactory end-point to pip config
      run: python "${{github.workspace}}/.github/scripts/update_pip_conf.py"
      shell: bash
      working-directory: ${{inputs.working_directory}}
    - name: build wheel
      run: python ${{ inputs.package_file }} bdist_wheel
      shell: bash
      working-directory: ${{inputs.working_directory}}
    - id: wheel
      run: python "${{github.workspace}}/.github/scripts/get_wheel_filename.py" --package-file ${{ inputs.package_file }} --set-gh-actions-var wheel-file
      shell: bash
      working-directory: ${{inputs.working_directory}}
    - name: install package
      run: python -m pip install "${{ steps.wheel.outputs.wheel-file }}"
      shell: bash
      working-directory: ${{inputs.working_directory}}
