name: Package and test on windows
on:
  push:
  pull_request:
  workflow_run:
    workflows: ["bump_version", "bump_patch_version"]
    branches: [main]
    types: 
      - completed
      - requested
jobs:
  build_test_windows:
    runs-on: windows-latest
    env:
      working-directory: "./{{ cookiecutter.library_name }}"
    defaults:
      run:
        shell: bash
        working-directory: "${{env.working-directory}}"
    if: "!contains(github.event.head_commit.message, '***SKIPBUILD***')"
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ '3.6' ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Build and install package
        uses: "./.github/actions/build-install-package"
        with:
          working_directory: "${{ env.working-directory }}"
      - name: run unit tests
        run: pytest
        working-directory: "./tests"
